module.exports = {
  projects: [
    '<rootDir>/apps/realworld-example-app',
    '<rootDir>/apps/feature-article',
    '<rootDir>/apps/feature-profile',
    '<rootDir>/apps/feature-tag',
    '<rootDir>/apps/feature-user',
    '<rootDir>/libs/models',
    '<rootDir>/libs/shared',
    '<rootDir>/libs/auth',
    '<rootDir>/libs/data-access',
    '<rootDir>/libs/editor',
    '<rootDir>/libs/home',
    '<rootDir>/libs/ngrx-error',
    '<rootDir>/libs/ngrx-forms',
    '<rootDir>/libs/profile',
    '<rootDir>/libs/ngrx-router',
    '<rootDir>/libs/settings',
    '<rootDir>/apps/conduit',
    '<rootDir>/libs/api',
    '<rootDir>/libs/article',
    '<rootDir>/libs/article-list',
  ],
};
